version: 2

jobs:
  "test":
    docker: &DOCKERIMAGE
      - image: jenkinsrise/cci-latest-node-with-gcloud:0.0.1
    steps:
      - checkout
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run test
          no_output_timeout: 1m

  "deploy_beta":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run:
          name: Deploy
          command: npm run deploy
      - run:
          name: Update version on GCS
          command: |
            echo Updating to version $(cat latest-chrome-player-version)
            gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
            gsutil cp latest-chrome-player-version gs://install-versions.risevision.com/latest-chrome-player-beta-version
            gsutil setmeta -h "Cache-Control:private, max-age=0" -h "Content-Type:text/plain" gs://install-versions.risevision.com/latest-chrome-player-beta-version
            gsutil acl ch -u AllUsers:R gs://install-versions.risevision.com/latest-chrome-player-beta-version

  "dist":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Generate zip
          command: NODE_ENV=production npm run dist
      - store_artifacts:
          path: dist/app.zip
      - persist_to_workspace:
          root: .
          paths:
            - latest-chrome-player-version

  "publish-version":
    docker: *DOCKERIMAGE
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: node-cache-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - run: git tag $(cat latest-chrome-player-version)
      - run: git push origin $(cat latest-chrome-player-version)
      - run: git clone git@github.com:Rise-Vision/private-keys.git
      - run:
          name: Update version on GCS
          command: |
            echo Updating to version $(cat latest-chrome-player-version)
            gcloud auth activate-service-account 452091732215@developer.gserviceaccount.com --key-file private-keys/storage-server/rva-media-library-ce0d2bd78b54.json
            gsutil cp latest-chrome-player-version gs://install-versions.risevision.com
            gsutil setmeta -h "Cache-Control:private, max-age=0" -h "Content-Type:text/plain" gs://install-versions.risevision.com/latest-chrome-player-version
            gsutil acl ch -u AllUsers:R gs://install-versions.risevision.com/latest-chrome-player-version

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - "test"
      - "deploy_beta":
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - "dist":
          requires:
            - test
          filters:
            branches:
              only:
                - build/stable
      - "manual_upload_to_webstore":
          type: approval
          requires:
           - dist
          filters:
            branches:
              only:
                - build/stable
      - "publish-version":
          requires:
            - manual_upload_to_webstore
          filters:
            branches:
              only:
                - build/stable
